version: "2"

run:
  concurrency: 4
  timeout: 2m

linters:
  enable:
    - revive
    - govet
    - errcheck
    - staticcheck
    - goconst
    - misspell
    - unconvert
    - unparam
    - ineffassign
    - gocritic

  settings:
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
        - name: empty-lines
        - name: if-return
        - name: var-naming
        - name: receiver-naming
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - opinionated
      disabled-checks:
        - unnecessaryBlock
